### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Seanny123**
Fixed typoes

### CODE REVIEW

**Comment by Seanny123** [comment]
Switched to mark-down

**Comment by Seanny123** [comment]
Sorry about that. Still learning how to use git.

**Comment by floweisshardt** [comment]
sorry, but that's not the official way how to build rosbuild packages. see http://wiki.ros.org/roscpp_tutorials/Tutorials/ and http://wiki.ros.org/rosbuild

**Comment by Seanny123** [comment]
Oh yes. I've figured that out now. Forgot to delete myself. Thanks for taking the trouble!

**Pull request closed without merging**
