### PR TITLE
Move 3d mapping msgs

### PR DESCRIPTION
**Pull request by fmessmer**
@ipa-rmb FYI
let's merge once everything is settled:
- `cob_perception_common`: done in this PR
- `cob_environment_perception`: https://github.com/ipa320/cob_environment_perception/pull/35
- `cob_object_perception`: nothing to be done, issue tracked in https://github.com/ipa320/cob_object_perception/issues/43
- `cob_scenario_states`

I'll keep you updated!

### CODE REVIEW

**Comment by fmessmer** [comment]
@ipa-rmb
Quick question: I don't like to much that `cob_perception_common` now depends on `cob_object_perception` (because `cob_3d_mapping_msgs` depends on `cob_object_detection_msgs`). Should we also move `cob_object_detection_msgs` into `cob_perception_common` to have all message definitions here in `cob_perception_common`?

**Comment by ipa-rmb** [comment]
It is already there :-)

**Comment by fmessmer** [comment]
ups, my bad!

Can you then please give the combo 
- https://github.com/ipa-fxm/cob_perception_common/tree/move_3d_mapping_msgs
- https://github.com/ipa-fxm/cob_environment_perception/tree/remove_cob_3d_mapping_msgs

a quick test whether it works as expected?
It should not have any effect on `cob_object_perception`...

**Comment by ipa-rmb** [comment]
It compiles on my machine. I do not have a quick test but it looks good. We can merge it.

**Comment by fmessmer** [comment]
compiles on my machine and travis is happy, too....feel free to merge the two PRs...I'll then continue to fix `cob_scenario_states`

**Pull request merged**
