### PR TITLE
test noetic

### PR DESCRIPTION
**Pull request by fmessmer**

### CODE REVIEW

**Comment by fmessmer** [comment]
@ipa-rmb @ipa-jcl @ipa-fog @ipa-foj (and all other perception guys at IPA)
@ipa-fez @ipa-owner-fez @ipa-jba @ipa-owner-jba 

I'm very tempted to remove `cob_vision_utils` from this repo (and also `cob_camera_sensors` from `cob_driver`)
if there is no strong argument against either of those...it will happen...

**Comment by ipa-rmb** [comment]
It should be ok for melodic and newer, but there are still some Installations that use these packages in indigo or kinetic (correct, @ipa-jcl?). 
Do you apply such changes to this indigo_dev branch (it would not work together with the other software in indigo anymore if the package is removed) or do you create a new branch? A tag would be very useful anyways in this branch if you do not create a new one. Or maybe it would make sense to split off another indigo_dev_backwards_compatibility branch before removing packages.

**Comment by fmessmer** [comment]
@ipa-rmb 
well those packages would still be available under the old tag (=previous release) - for both repos `cob_perception_common` and `cob_driver`
but I'd rather not create new branches - if possible

**Comment by fmessmer** [comment]
at the moment I'm still trying to figure out why dependencies to CV (`cv_bridge`) or PCL (`pcl_ros`) take suuuper-long to `rosdep install` for noetic - compared to kinetic/melodic - making the travis job actually fail due timeout
maybe the noetic docker image is much more minimal than the one used for kinetic/melodic respectively

mayb @ipa-mdl knows why or has a hint...

**Comment by fmessmer** [comment]
I'll test with `DOCKER_IMAGE=ros:noetic-perception` to see whether this achieves some speed-up
however, we might want to investigate whether the dependencies are in fact minimal already, i.e. do we really need `libopencv-dev` and `libpcl-all-dev`?

**Comment by fmessmer** [comment]
apparently, already the `ros:noetic-perception` docker image takes forever to download...
I don't know what changed but it seems that something in the perception dependencies is excessively big now

**Comment by fmessmer** [comment]
@ipa-rmb @ipa-jcl 
`cob_vision_utils` does not compile under `noetic` - thus, I removed it

**Comment by ipa-fog** [comment]
I guess this should be fine. We already discussed that we might separate cob and "general IPA" perception common code

**Review by ipa-fog — APPROVED** [review]

**Review by ipa-rmb — APPROVED** [review]
Can you please provide additional information to the new tag that you are dropping the indigo+kinetic compatibility for other packages with dependencies to cob_perception_common? It is quite hard to remember that version 0.6.15 was the last one compatible.

**Comment by fmessmer** [comment]
`0.6.15` will have `cob_vision_utils` still included
`0.6.16` will have it removed

**Pull request merged**
