### PR TITLE
[kinetic] use industrial_ci for travis

### PR DESCRIPTION
**Pull request by benmaidel**

### CODE REVIEW

**Comment by ipa-rmb** [comment]
Travis fails...

**Comment by benmaidel** [comment]
This is strange. Looks like travis exceeds the log size of 4MB and failes. @ipa-fmw do you see the same?

**Comment by floweisshardt** [comment]
yes, we had this issue too with the care-o-bot build scripts for travis. We solved it with surpressing output with `2>&1`.

I found another thread using a script to fill a log file and then only show the tail to limit log file size: http://stackoverflow.com/questions/26082444/how-to-work-around-travis-cis-4mb-output-limit (haven't tried this yet.) Would make sense to open an issue or PR to ros-industrial/industrial-ci.

**Comment by benmaidel** [comment]
there is already an issue open https://github.com/ros-industrial/industrial_ci/issues/66
But no solution so far.

**Comment by benmaidel** [comment]
Fine to approve :)

**Comment by ipa-rmb** [comment]
If everybody is fine with the file, I will merge.

**Review by floweisshardt — APPROVED** [review]

**Pull request merged**
