### PR TITLE
Removed unnecessary cmake_modules

### PR DESCRIPTION
**Pull request by ipa-rmb**
Before merging, how do I remove the unnecessary commits (those without any effect) that were squashed in the last PR?

### CODE REVIEW

**Comment by fmessmer** [comment]
this time: `git rebase origin-320/indigo_dev`
next time: start using feature-branches :wink:

**Review by fmessmer — APPROVED** [review]

**Comment by fmessmer** [comment]
Hmm, I tested the github rebase&merge option...it did the right thing: rebase...but I guess squashing would have been better as now the add-modify-remove grasp service part is included as well....
one more argument for only providing properly cleaned-up, squashed and rebased PRs from a feature-branch :stuck_out_tongue_winking_eye:

**Comment by fmessmer** [comment]
@ipa-rmb could you re-release `cob_perception_common` for both indigo and kinetic as your fix fixes a few things on the build farm...

**Comment by bbrito** [comment]
@ipa-rmb  Where is the grasping service now? We need it for the picking scenario...

**Comment by ipa-rmb** [comment]
back in order picking

**Pull request merged**
