### PR TITLE
Revised cob_image_flip, added msgs

### PR DESCRIPTION
**Pull request by ipa-rmb**
- complete revision of cob_image_flip
  - simple configuration from yaml file
  - rotation modi: fixed angle and automatic angle determination from tf
  - automatic angle with option to round rotation in 90 deg steps
- moved the cob_people_detections_msgs package to cob_perception_common
- catkin conversion

### CODE REVIEW

**Comment by fmessmer** [comment]
@ipa-rmb 
The names of the executable/libraries/classes have changed from `kinect_image_flip*` to `image_flip*`, right?

Could you please adjust the launch files:
- https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/drivers/image_flip.launch
- https://github.com/ipa320/cob_robots/blob/indigo_dev/cob_bringup/drivers/image_flip_nodelet.launch
  and the config files for the robots **cob4-1** and **cob4-2**?
  Where else do we need to adjust something?

@ipa-fmw @ipa-nhg

**Comment by NadiaHG** [comment]
https://github.com/ipa320/cob_robots/pull/277

**Comment by fmessmer** [comment]
with the adaption made in https://github.com/ipa320/cob_robots/pull/277 and https://github.com/ipa320/cob_robots/pull/279, this should be good to merge

@ipa-nhg, @ipa-rmb please give final ok

**Comment by ipa-rmb** [comment]
Visual review OK

**Comment by floweisshardt** [comment]
@ipa-rmb did you trigger a new release? or why did the version number and changelog change?

**Comment by floweisshardt** [comment]
visual review: OK

**Comment by floweisshardt** [comment]
merge together with ipa320/cob_robots#277 and ipa320/cob_robots#279

**Pull request merged**
